# Generated by Django 5.1.5 on 2025-02-17 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100, null=True)),
                ('plan_date', models.DateField(null=True)),
                ('notes', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyball.team')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyball.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('opponent', models.CharField(max_length=100, null=True)),
                ('my_team_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('winning_pitcher', models.CharField(max_length=100, null=True)),
                ('losing_pitcher', models.CharField(max_length=100, null=True)),
                ('save_pitcher', models.CharField(max_length=100, null=True)),
                ('home_run', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyball.team')),
            ],
        ),
    ]
